id: opecha:P000369
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC309
  title: 'སྒམ་པོའི་གདན་རབས་རིམ་བྱོན་གྱི་གསུང་འབུམ། '
  volume:
    d325b93629994ab7aee658705ca7a0ae:
      image_group_id: I4PD2738
      title: Volume 1 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 1
      total_pages: 354
    5171026c5b0545b29cd107d10d001984:
      image_group_id: I4PD2739
      title: Volume 2 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 2
      total_pages: 382
    4c7a67e371df4ad1b73a53d7d195d7d4:
      image_group_id: I4PD2740
      title: Volume 3 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 3
      total_pages: 338
    744d8bac93ad410dbafa6aeccc4e7c0d:
      image_group_id: I4PD2741
      title: Volume 4 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 4
      total_pages: 338
    e898c8e2b267492b9ac7dc46388515ae:
      image_group_id: I4PD2742
      title: Volume 5 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 5
      total_pages: 474
    24abb84414f3485caff7e44a1d5ed361:
      image_group_id: I4PD2743
      title: Volume 6 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 6
      total_pages: 350
    4e8cddf7504348fd8b4d2ff9de1cfd4d:
      image_group_id: I4PD2744
      title: Volume 7 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 7
      total_pages: 314
    bebd4a4c69c845188b14c02818cc5ee5:
      image_group_id: I4PD2745
      title: Volume 8 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 8
      total_pages: 506
    633f5471bdac4dc78eb716d31f097366:
      image_group_id: I4PD2746
      title: Volume 9 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 9
      total_pages: 294
    5ca5d73d81cd4b34895b9eef42f68930:
      image_group_id: I4PD2747
      title: Volume 10 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 10
      total_pages: 336
    5c591210da4942ce864d7eed596ad057:
      image_group_id: I4PD2748
      title: Volume 11 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 11
      total_pages: 372
    14649e9730574c65b0f9fc1487ee4e4b:
      image_group_id: I4PD2749
      title: Volume 12 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 12
      total_pages: 350
    1aef902cf55b42c4bf1078800187532c:
      image_group_id: I4PD2750
      title: Volume 13 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 13
      total_pages: 340
    a44c0e8f4a6044f88eaa4757c5d685e4:
      image_group_id: I4PD2751
      title: Volume 14 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 14
      total_pages: 452
    700ddc38fa8b4de29081d6a1602c06a6:
      image_group_id: I4PD2752
      title: Volume 15 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 15
      total_pages: 374
    8456c0e01b3248c698d4852da3b7b60f:
      image_group_id: I4PD2753
      title: Volume 16 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 16
      total_pages: 366
    1091e0aec16e4b0289ec0fe8a79b0517:
      image_group_id: I4PD2754
      title: Volume 17 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 17
      total_pages: 346
    6996d09338844b6daa32ee3b0b64e108:
      image_group_id: I4PD2755
      title: Volume 18 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 18
      total_pages: 382
    7f5f9ec7933340e5913a4ab5121e64aa:
      image_group_id: I4PD2756
      title: Volume 19 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      volume_number: 19
      total_pages: 410
  author: ''
ebook_metadata:
  title: 'སྒམ་པོའི་གདན་རབས་རིམ་བྱོན་གྱི་གསུང་འབུམ། '
  author: ''
  sku: P000369
  cover: cover.jpg
  layers:
  - pagination
