id: I0A89BB97
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T08:40:12+00:00'
last_modified: '2022-06-10T05:04:05.938367+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC309
  title: 'སྒམ་པོའི་གདན་རབས་རིམ་བྱོན་གྱི་གསུང་འབུམ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D42D:
      image_group_id: I4PD2738
      title: Volume 1 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 354
      order: 1
      base_file: D42D.txt
    1E34:
      image_group_id: I4PD2739
      title: Volume 2 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 382
      order: 2
      base_file: 1E34.txt
    '3806':
      image_group_id: I4PD2740
      title: Volume 3 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 338
      order: 3
      base_file: 3806.txt
    7DDA:
      image_group_id: I4PD2741
      title: Volume 4 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 338
      order: 4
      base_file: 7DDA.txt
    E519:
      image_group_id: I4PD2742
      title: Volume 5 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 474
      order: 5
      base_file: E519.txt
    '7416':
      image_group_id: I4PD2743
      title: Volume 6 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 350
      order: 6
      base_file: 7416.txt
    D038:
      image_group_id: I4PD2744
      title: Volume 7 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 314
      order: 7
      base_file: D038.txt
    '9035':
      image_group_id: I4PD2745
      title: Volume 8 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 506
      order: 8
      base_file: 9035.txt
    C68C:
      image_group_id: I4PD2746
      title: Volume 9 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 294
      order: 9
      base_file: C68C.txt
    '6671':
      image_group_id: I4PD2747
      title: Volume 10 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 336
      order: 10
      base_file: 6671.txt
    '2200':
      image_group_id: I4PD2748
      title: Volume 11 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 372
      order: 11
      base_file: 2200.txt
    AE6D:
      image_group_id: I4PD2749
      title: Volume 12 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 350
      order: 12
      base_file: AE6D.txt
    4CFB:
      image_group_id: I4PD2750
      title: Volume 13 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 340
      order: 13
      base_file: 4CFB.txt
    0818:
      image_group_id: I4PD2751
      title: Volume 14 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 452
      order: 14
      base_file: 0818.txt
    '4705':
      image_group_id: I4PD2752
      title: Volume 15 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 374
      order: 15
      base_file: 4705.txt
    46FD:
      image_group_id: I4PD2753
      title: Volume 16 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 366
      order: 16
      base_file: 46FD.txt
    8A62:
      image_group_id: I4PD2754
      title: Volume 17 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 346
      order: 17
      base_file: 8A62.txt
    54E4:
      image_group_id: I4PD2755
      title: Volume 18 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 382
      order: 18
      base_file: 54E4.txt
    E8A8:
      image_group_id: I4PD2756
      title: Volume 19 of sgam po'i gdan rabs rim byon gyi gsung 'bum/
      total_pages: 410
      order: 19
      base_file: E8A8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
